import type { Metadata } from "next";
import localFont from "next/font/local";
import {Sorts_Mill_Goudy} from "next/font/google";
import "./globals.css";


const urwBold = localFont({
  src: "./fonts/URWClassico-Bold.ttf",
  variable: "--font-urw-bold",
  weight: "100 900",
})

const urwRegular = localFont({
  src: "./fonts/URWClassico-Regular.ttf",
  variable: "--font-urw-regular",
  weight: "100 400 900",
})

const sortsMillyGoudy = Sorts_Mill_Goudy({
  subsets: ["latin"],
  weight: ['400'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sortsMillyGoudy.className} ${urwBold.variable} ${urwRegular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
